---

- name: Install MariaDB server and client
  apt: 
    pkg:
    - mariadb-server
    - mariadb-client
    - libmysqlclient-dev

- name: Install mysql-python
  pip:
    name: MySQL-python

- name: Start MariaDB Service
  service: name={{ db_service }} state=started enabled=yes

