---

#
# Apache
#

- name: Write Apache2 vhost conf file
  template: src=apache-01-drupal.conf.j2 dest=/etc/apache2/sites-available/01-drupal.conf
  when: webserver_type == "apache"

- name: Remove Apache2 default vhost from sites-enabled
  file:
    path: "/etc/apache2/sites-available/000-default.conf"
    state: absent
  when: webserver_type == "apache"    

- name: Create Apache2 sites-enabled symlink for new vhosts
  file: 
    src: "/etc/apache2/sites-available/01-drupal.conf"
    dest: "/etc/apache2/sites-enabled/01-drupal.conf"
    state: link 
  notify: restart apache2  
  when: webserver_type == "apache"


#
# Nginx
#

- name: Write Nginx conf file
  template: src=nginx-drupal.j2 dest=/etc/nginx/sites-available/drupal
  when: webserver_type == "nginx"

- name: Remove Nginx default conf from sites-enabled
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  when: webserver_type == "nginx"    

- name: Create sites-enabled symlink for new vhosts
  file: 
    src: "/etc/nginx/sites-available/drupal"
    dest: "/etc/nginx/sites-enabled/drupal"
    state: link 
  notify: restart nginx  
  when: webserver_type == "nginx"
