---

- name: Add bionic universe repository for Ubuntu Bionic (required for PHP modules)
  apt_repository: 
    repo: deb http://archive.ubuntu.com/ubuntu bionic universe
    state: present
  when: ansible_distribution_release == 'bionic'

- name: Add bionic-security universe repository for Ubuntu Bionic 
  apt_repository: 
    repo: deb http://archive.ubuntu.com/ubuntu bionic-security universe (required for PHP modules)
    state: present
  when: ansible_distribution_release == 'bionic'  

- name: Add bionic-updates universe repository for Ubuntu Bionic (required for PHP modules)
  apt_repository: 
    repo: deb http://archive.ubuntu.com/ubuntu bionic-updates universe
    state: present
  when: ansible_distribution_release == 'bionic'  

- name: Update apt package repos (apt-get update)
  apt:
    update_cache: yes

- name: Install python modules and git
  apt:
    pkg:
    - python3
    - python3-pip
    - python3-dev
    - git
    - unzip
    - net-tools

- name: Add "{{ apache_group }}" group
  group:
    name: "{{ apache_group }}"
    state: present  
  become: yes  

- name: Add "{{ apache_user }}" user with the home dir /home/{{ os_user }}/ (so we can set ulimits)
  user:
    name: "{{ apache_user }}"
    group: "{{ apache_group }}"
    home: /home/{{ apache_user }}/
    shell: /bin/bash
    comment: WWW Data User
  become: yes
