---

- name: Check for Drupal Install
  stat: 
    path: "{{ drupal_base_path }}/composer.json"
  register: composer_run    

- name: Make sure drupal_base_path doesn't exist (first run) as Composer needs a blank directory
  when: not composer_run.stat.exists  
  file:
    path: "{{ drupal_base_path }}"
    state: absent

- name: Create Drupal base directory before Composer run
  file:
    path: "{{ drupal_base_path }}"
    state: directory
    owner: "{{ apache_user }}"    
    group: "{{ apache_group }}"

- name: Install Drupal with Composer
  composer:
    command: create-project
    arguments: drupal/recommended-project drupal --stability stable --no-interaction
    working_dir: "{{ drupal_base_path }}/.."
    prefer_dist: yes
  when: not composer_run.stat.exists
  become: true

- name: Install Drush with Composer
  become: false    
  composer:
     command: require 
     arguments: drush/drush
     working_dir: "{{ drupal_base_path }}"

- name: Set {{ drupal_base_path }} owner & group recursively
  file:
    path: "{{ drupal_base_path }}"
    state: directory
    owner: "{{ apache_user }}"    
    group: "{{ apache_group }}"
    recurse: yes
  become: yes       