---

- name: Check for Drupal Install
  stat: 
    path: "{{ drupal_base_path }}/composer.json"
  register: composer_run    

- name: Make sure drupal_base_path doesn't exist (first run) as Composer needs a blank directory
  file:
    path: "{{ drupal_base_path }}"
    state: absent
  when: not composer_run.stat.exists  

- name: Create Drupal base directory before Composer run
  file:
    path: "{{ drupal_base_path }}"
    state: directory
    owner: "{{ apache_user }}"    
    group: "{{ apache_group }}"

- name: Install Drupal with Composer (via command module due to issue with composer module)
  command: 
    cmd: composer create-project drupal/recommended-project drupal --stability stable --no-interaction
    chdir: "{{ drupal_base_path }}/.."
  when: not composer_run.stat.exists
  become: true

- name: Install Drush with Composer (via command module due to issue with composer module)
  command: 
    cmd: composer require drush/drush --no-interaction
    chdir: "{{ drupal_base_path }}"
  become: true 

- name: Set {{ drupal_base_path }} owner & group recursively
  file:
    path: "{{ drupal_base_path }}"
    state: directory
    owner: "{{ apache_user }}"    
    group: "{{ apache_group }}"
    recurse: yes
  become: yes       